### ISSUE TITLE
Does not work when screen turns off for more than 20-60 seconds

### ISSUE THREAD

**Issue by ghost** [nschwermann/android-websocket-example#1]
I am aware that this is a very old project, however...

Did you try it with a recent Android version? I just tried it on Android 4.2.2.

At first everything seems fine. However, after turning off the screen and waiting for some seconds (>20), the example app did not receive anything anymore. Even after turning back on it does not work again. It seems there is not enough time to acquire the wakelock. Or readByte() does not return at all. Hard to tell. Any thought? Anybody?

**Comment by nschwermann** [comment]
It has been a while since I've touched this but I do believe 4.2 had been out when I wrote it.  Does the companion web app get the websocket push if you have multiple browsers with it open?  I think my server has a bit more bit-decay than the android app.

**Comment by ghost** [comment]
I did not try multiple browsers but one browser and Android app. That worked pretty good. However, the actual issue seems to be an Android "problem". It is going into deep sleep and network event will not wake it. Obviously that is for saving energy and they want to make you use GCM if you need instant push messages. This this is nothing which could be fixed here easily. So I am closing this issue.

PS: An optional wake lock which avoids deep sleep might be nice.

**Comment by nschwermann** [comment]
In my testing if the TCP connection was established any network activity would cause a brief wakeup with enough time for my app to grab a wakelock and pull down the rest of the push.  However, I only tested on a very small subset of kernals/devices.

GCM uses the same technique as far as I know. I am positive Google uses TCP and doesn't hold a continuous wakelock either.

**Comment by ghost** [comment]
> any network activity would cause a brief wakeup

Yes, that is what I also read. And it works within the aprrox first 60 seconds after switching of the display. However, if the device is unplugged and idle for 5 minutes, it does not wake up anymore by network events. To be precise, I used Java NIO, and the select() method(*) did return when the server sends a push message. If you could show me some Android code which reliably receives TCP packets, I'd be more than happy!

(*) https://developer.android.com/reference/java/nio/channels/Selector.html#select%28%29

**Comment by ghost** [comment]
How interesting! Some curious observation I want to share:

If the Google Services Framework (process com.google.process.gapps) is running (even though I do not use it!), background communication works much better. Following test:

Android client opens TCP connection to server and sends every 5 minutes a "ping" (using alarm BroadcastReceiver). Server sends after delay of 35 seconds a "pong" back. Client responds with "ack". When server receives "ack" it increases delay time by 25 seconds.
This way I can see how the communication went without waking the Android device, just by looking at the server log.

without Google Services Framework:

```
2015/01/27 11:28:05: accepted-client: PyroClient[IP@43619]
2015/01/27 11:33:05: received "ping" from PyroClient[IP@43619]
2015/01/27 11:33:05: Going to respond to ping in 35 seconds.
2015/01/27 11:33:40: Sending pong now.
2015/01/27 11:34:01: received "ack" from PyroClient[IP@43619]
2015/01/27 11:34:01: Increased pongDelaySeconds to 60 seconds. ackTime: 21
2015/01/27 11:38:05: received "ping" from PyroClient[IP@43619]
2015/01/27 11:38:05: Going to respond to ping in 60 seconds.
2015/01/27 11:39:05: Sending pong now.
2015/01/27 11:39:24: IOException while reading channel
```

with Google Services Framework running:

```
2015/01/27 12:00:53: accepted-client: PyroClient[IP@34720]
2015/01/27 12:05:53: received "ping" from PyroClient[IP@34720]
2015/01/27 12:05:53: Going to respond to ping in 35 seconds.
2015/01/27 12:06:28: Sending pong now.
2015/01/27 12:06:28: received "ack" from PyroClient[IP@34720]
2015/01/27 12:06:28: Increased pongDelaySeconds to 60 seconds. ackTime: 0
2015/01/27 12:10:53: received "ping" from PyroClient[IP@34720]
2015/01/27 12:10:53: Going to respond to ping in 60 seconds.
2015/01/27 12:11:53: Sending pong now.
2015/01/27 12:13:11: received "ack" from PyroClient[IP@34720]
2015/01/27 12:13:11: Increased pongDelaySeconds to 85 seconds. ackTime: 78
2015/01/27 12:15:54: received "ping" from PyroClient[IP@34720]
2015/01/27 12:15:54: Going to respond to ping in 85 seconds.
2015/01/27 12:17:19: Sending pong now.
2015/01/27 12:17:30: received "ack" from PyroClient[IP@34720]
2015/01/27 12:17:30: Increased pongDelaySeconds to 110 seconds. ackTime: 10
2015/01/27 12:20:54: received "ping" from PyroClient[IP@34720]
2015/01/27 12:20:54: Going to respond to ping in 110 seconds.
2015/01/27 12:22:44: Sending pong now.
2015/01/27 12:22:56: received "ack" from PyroClient[IP@34720]
2015/01/27 12:22:56: Increased pongDelaySeconds to 135 seconds. ackTime: 12
```

So, it can take more than a minute until the Android device actual notices an incoming paket but the paket is not lost and the TCP connection does not break.

**Comment by nschwermann** [comment]
Interesting, you might try adjusting the heartbeat in my example to the
same timing. If I remember right I have it at like 15 minutes.

On Tue, Jan 27, 2015 at 5:26 AM, LukeOwncloud notifications@github.com
wrote:

> How interesting! Some curious observation I want to share:
> 
> If the Google Services Framework (process com.google.process.gapps) is
> running, background communication works much better (even though I do not
> use it!). Following test:
> 
> Android client opens TCP connection to server and sends every 5 minutes a
> "ping" (using alarm BroadcastReceiver). Server sends after delay of 35
> seconds a "pong" back. Client responds with "ack". When server receives
> "ack" it increases delay time by 25 seconds.
> This way I can see how the communication went without waking the Android
> device, just by looking at the server log.
> 
> without Google Services Framework:
> 
> 2015/01/27 11:28:05: accepted-client: PyroClient[IP@43619]
> 2015/01/27 11:33:05: received "ping" from PyroClient[IP@43619]
> 2015/01/27 11:33:05: Going to respond to ping in 35 seconds.
> 2015/01/27 11:33:40: Sending pong now.
> 2015/01/27 11:34:01: received "ack" from PyroClient[IP@43619]
> 2015/01/27 11:34:01: Increased pongDelaySeconds to 60 seconds. ackTime: 21
> 2015/01/27 11:38:05: received "ping" from PyroClient[IP@43619]
> 2015/01/27 11:38:05: Going to respond to ping in 60 seconds.
> 2015/01/27 11:39:05: Sending pong now.
> 2015/01/27 11:39:24: IOException while reading channel
> 
> with Google Services Framework running:
> 
> 2015/01/27 12:00:53: accepted-client: PyroClient[134.28.77.229@34720]
> 2015/01/27 12:05:53: received "ping" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:05:53: Going to respond to ping in 35 seconds.
> 2015/01/27 12:06:28: Sending pong now.
> 2015/01/27 12:06:28: received "ack" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:06:28: Increased pongDelaySeconds to 60 seconds. ackTime: 0
> 2015/01/27 12:10:53: received "ping" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:10:53: Going to respond to ping in 60 seconds.
> 2015/01/27 12:11:53: Sending pong now.
> 2015/01/27 12:13:11: received "ack" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:13:11: Increased pongDelaySeconds to 85 seconds. ackTime: 78
> 2015/01/27 12:15:54: received "ping" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:15:54: Going to respond to ping in 85 seconds.
> 2015/01/27 12:17:19: Sending pong now.
> 2015/01/27 12:17:30: received "ack" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:17:30: Increased pongDelaySeconds to 110 seconds. ackTime: 10
> 2015/01/27 12:20:54: received "ping" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:20:54: Going to respond to ping in 110 seconds.
> 2015/01/27 12:22:44: Sending pong now.
> 2015/01/27 12:22:56: received "ack" from PyroClient[134.28.77.229@34720]
> 2015/01/27 12:22:56: Increased pongDelaySeconds to 135 seconds. ackTime: 12
> 
> So, it can take more than a minute until the Android device actual notices
> an incoming paket but the paket is not lost and the TCP connection does not
> break.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schwiz/android-websocket-example/issues/1#issuecomment-71631877
> .

## 

_Nathan Schwermann_
_785-312-0080_
_http://schwiz.net http://schwiz.net_
